test_name: Create new project without modules

marks:
  - Working
  - usefixtures:
    - generate_name
    - generate_identifier
    - get_name
    - get_identifier

includes:
  - !include constants.yaml

stages:
  - name: Create project

    request:
      url: "{protocol}://{host}/projects.json"
      method: POST
      headers:
        X-Redmine-API-Key: "{api_key}"
        Content-Type: "{content_type}"
      json:
        project:
          name: '{generate_name}'
          identifier: '{generate_identifier}'
          description: asdasdasdasd

    response:
      status_code: 201
      body:
        project:
          name: "{get_name}"
          identifier: "{get_identifier}"
          status: 1
          is_public: true