test_name: Modify project name

marks:
  - Working
  - usefixtures:
    - generate_name
    - generate_identifier
    - get_name
    - get_identifier

includes:
  - !include constants.yaml

stages:
  - name: Create project

    request:
      url: "{protocol}://{host}/projects.json"
      method: POST
      headers:
        X-Redmine-API-Key: "{api_key}"
        Content-Type: "{content_type}"
      json:
        project:
          name: '{generate_name}'
          identifier: '{generate_identifier}'
          description: asdasdasdasd

    response:
      status_code: 201
      save:
        body:
          id: project.id

  - name: Modify project name
    request:
      url: "{protocol}://{host}/projects/{id}.json"
      method: PUT
      headers:
        X-Redmine-API-Key: "{api_key}"
        Content-Type: "{content_type}"
      json:
        project:
          name: new name
          description: new description

    response:
      status_code: 200

  - name: Get updated project
    request:
      url: "{protocol}://{host}/projects/{id}.json"
      method: GET
      headers:
        X-Redmine-API-Key: "{api_key}"
        Content-Type: "{content_type}"

    response:
      status_code: 200
      body:
        project:
          id: !int "{id}"
          name: new name
          description: new description
