test_name: Deleate a created project

marks:
  - Working
  - usefixtures:
    - generate_name
    - generate_identifier
    - get_name
    - get_identifier

includes:
  - !include constants.yaml

stages:
  - name: Create project
    request:
      url: "{protocol}://{host}/projects.json"
      method: POST
      headers:
        X-Redmine-API-Key: "{api_key}"
        Content-Type: "{content_type}"
      json:
        project:
          name: '{generate_name}'
          identifier: '{generate_identifier}'
          description: asdasdasdasd

    response:
      status_code: 201
      save:
        body:
          id: project.id

  - name: Delete project
    request:
      url: "{protocol}://{host}/projects/{id}.json"
      method: DELETE
      headers:
        X-Redmine-API-Key: "{api_key}"
        Content-Type: "{content_type}"

    response:
      status_code: 200
