test_name: Create projects with same identifier

marks:
  - Working
  - usefixtures:
    - generate_name
    - generate_identifier
    - get_name
    - get_identifier

stages:
  - name: Create first project

    request:
      url: &url "{protocol}://{host}/projects.json"
      method: POST
      headers: &header
        X-Redmine-API-Key: "{api_key}"
        Content-Type: "{content_type}"
      json:
        project:
          name: '{generate_name}'
          identifier: '{generate_identifier}'

    response:
      status_code: 201
      body:
        project:
          name: !!str "{get_name}"
          identifier: !!str "{get_identifier}"
          status: !int 1
          is_public: !bool true
      save:
        body:
          identifier: project.identifier
          name: project.name

  - name: Create second project

    request:
      url: *url
      method: POST
      headers: *header
      json:
        project:
          name: !!str name
          identifier: !!str identifier

    response:
      status_code: !int 422
      body:
        errors:
          - "Identifier has already been taken"