test_name: Create project with identifier equal to existing id

marks:
  - Working
  - probando
  - usefixtures:
    - generate_name
    - generate_identifier
    - get_name
    - get_identifier

# se realiza en el comando de ejecucion de los tests
# includes:
#   - !include /Users/cizquierdo/PycharmProjects/tavern/constants.yaml

stages:
  - name: Create first project

    request:
      url: &url_post "{protocol}://{host}/projects.json"
      method: POST
      headers: &header
        X-Redmine-API-Key: "{api_key}"
        Content-Type: "{content_type}"
      json:
        project:
          name: '{generate_name}'
          identifier: '{generate_identifier}'

    response:
      status_code: 201
      save:
        body:
          id: project.id

  - name: Create project with identifier equal to id of project created

    request:
      url: *url_post
      method: POST
      headers: *header
      json:
        project:
          name: 'second project'
          identifier: !int '{id}'

    response:
      status_code: 422

  - name: Get project

    request:
      url: "{protocol}://{host}/projects/{id}.json"
      method: GET
      headers: *header

    response:
      status_code: 200
      body:
        project:
          name: '{get_name}'
          identifier: '{get_identifier}'
          id: !int '{id}'
