test_name: Create new issue with invalid status

marks:
  - Working
  - Issue
  - usefixtures:
      - generate_name
      - get_name
  - parametrize:
      key: project_identifier
      vals:
        - test_issues_project
  - parametrize:
      key: status_id
      vals:
        - 2
        - 3
        - 4
        - 5
        - 6
  - parametrize:
      key: status_id_exp
      vals:
        - 1

stages:
  - name: Get project id by name

    request:
      url: "{protocol}://{host}/projects/{project_identifier}.json"
      method: GET
      headers: &header
        X-Redmine-API-Key: "{api_key}"
        Content-Type: "{content_type}"

    response:
      status_code: 200
      body:
        project:
          identifier: "{project_identifier}"
      save:
        body:
          project_id: project.id
          project_name: project.name

  - name: Create issue

    request:
      url: "{protocol}://{host}/issues.json"
      method: POST
      headers: *header
      json:
        issue:
          project_id: '{project_id}'
          subject: '{generate_name}'
          status_id: '{status_id_exp}'

    response:
      status_code: 201
      body:
        issue:
          project:
            id: !int '{project_id}'
            name: '{project_name}'
          tracker:
            id: !anyint
            name: !anystr
          status:
            id: !int '{status_id_exp}'
          priority:
            id: !anyint
          subject: '{get_name}'

---

test_name: Create new issue with valid status

marks:
  - Working
  - Issue
  - usefixtures:
      - generate_name
      - get_name
  - parametrize:
      key: project_identifier
      vals:
        - test_issues_project
  - parametrize:
      key: status_id
      vals:
        - 1
  - parametrize:
      key: priority_id
      vals:
        - 1
        - 2
        - 3
        - 4
        - 5

stages:
  - name: Get project id by name

    request:
      url: "{protocol}://{host}/projects/{project_identifier}.json"
      method: GET
      headers: *header

    response:
      status_code: 200
      body:
        project:
          identifier: "{project_identifier}"
      save:
        body:
          project_id: project.id
          project_name: project.name

  - name: Create issue

    request:
      url: "{protocol}://{host}/issues.json"
      method: POST
      headers: *header
      json:
        issue:
          project_id: '{project_id}'
          subject: '{generate_name}'
          status_id: '{status_id}'
          priority_id: '{priority_id}'

    response:
      status_code: 201
      body:
        issue:
          project:
            id: !int '{project_id}'
            name: '{project_name}'
          tracker:
            id: !anyint
            name: !anystr
          status:
            id: !int '{status_id}'
          priority:
            id: !int '{priority_id}'
          subject: '{get_name}'
